image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser

tasks:
  - name: python
    init: |
      echo "export PYTHONPATH=src" >> ~/.bashrc
      pip install --upgrade pip
      pip install -r python/requirements.txt
    command: |
      cp -n python/defaults/* python/work/

  - name: react
    init: |
      cd $GITPOD_REPO_ROOTS/react/public
      ln -s ../../python/work/web web
      cd $GITPOD_REPO_ROOTS/react
      npm install
      cd $GITPOD_REPO_ROOTS

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - davidanson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - tomoki1207.pdf
